# @package _group_
_target_: mass_regression.datasets.higgs.HiggsDataModule
data_dir: /global/cscratch1/sd/schuya/mass_regression/data/fine_higgs
event_frac: 1.0
train_frac: 0.8
test_frac: 0.1
download: True
num_workers: 8
batch_size: ${train.batch_size}
features: [MET_X_Vis, MET_Y_Vis, La_Visx, La_Visy, La_Visz, La_VisE, Lb_Visx, Lb_Visy, Lb_Visz, Lb_VisE]
outputs: [Na_Genx, Na_Geny, Na_Genz, Nb_Genz]
attributes: [MET_X_Vis, MET_Y_Vis, La_Visx, La_Visy, La_Visz, La_VisE, Lb_Visx, Lb_Visy, Lb_Visz, La_VisE, Wa_Genm_squared, Wb_Genm_squared, H_Genm_squared]
fit_transforms: ${transforms.fit_transforms}
training_masses: ${dataset_range.training_masses}
testing_masses: ${dataset_range.testing_masses}