# @package _group_
_target_: datasets.higgs.HiggsDataModule
data_dir: /global/cscratch1/sd/schuya/mass_regression/data/higgs
num_events: 10000
num_train_events: 8000
num_test_events: 1000
download: False
num_workers: 8
num_epochs: ${train.num_epochs}
batch_size: ${train.batch_size}
features: [MET_X_Vis, MET_Y_Vis, La_Visx, La_Visy, La_Visz, La_Vism, Lb_Visx, Lb_Visy, Lb_Visz, La_Vism]
outputs: [Na_Genx, Na_Geny, Na_Genz, Nb_Genz]
attributes: [MET_X_Vis, MET_Y_Vis, La_Visx, La_Visy, La_Visz, La_Vism, Lb_Visx, Lb_Visy, Lb_Visz, La_Vism, Wa_Genm, Wb_Genm, H_Genm]