seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
defaults:
  - transforms: fit
  - train: slurm
  - dataset_range: higgs_400
  - dataset: h_ww_lnulnu
  - optimizer: sgd
  - scheduler: reduce_lr_on_plateau
  - dataset_criterion: h_ww_lnulnu_mixed
  - model: dnn
  - wandb: upload
  - checkpoint: top_1
  - early_stopping: 10_epochs