seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
defaults:
  - transforms: fit
  - train: slurm
  - dataset_range: higgs_all
  - dataset: h_ww_lnulnu
  - optimizer: adamw
  - scheduler: one_cycle
  - dataset_criterion: h_ww_lnulnu_mixed
  - model: dnn
  - wandb: upload
  - checkpoint: top_1
  - early_stopping: null