seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
criterion: nu
defaults:
  - train: single_gpu
  - dataset: single-higgs
  - metrics: default
  - optimizer: sgd
  - dataset/criterion: ${dataset}/${criterion}
  - model: dnn
  - wandb: active
  - checkpoint: top_1