seed: 1588147245
deterministic: False
init_ckpt: null
log_level: INFO
defaults:
  - transforms: fit
  - train: single_gpu
  - dataset: h_ww_lnulnu
  - optimizer: sgd
  - dataset_criterion: h_ww_lnulnu_nu
  - model: dnn
  - wandb: local
  - checkpoint: top_1